# This is a basic workflow to help you get started with Actions

name: Post Something

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  pull_request_review:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: My first step
       # && github.event.action == 'completed'  && startsWith(github.event.review.body, 'QA PASS')
       # if: ${{ github.event_name == 'pull_request_review' && github.event.action == 'completed' && github.event.pull_request.user.login == 'sumesh-sukumaran' }}
       run: echo ${{github.event.pull_request.body}}
